Update update_token.yml

diff --git a/.github/workflows/update_token.yml b/.github/workflows/update_token.yml
--- a/.github/workflows/update_token.yml
+++ b/.github/workflows/update_token.yml
@@ -22,11 +22,17 @@ jobs:
     - name: Install Google Chrome
       run: sudo apt-get install -y google-chrome-stable
 
-    - name: Download ChromeDriver
+    - name: Download specific ChromeDriver version
       run: |
-        LATEST_CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
-        echo "Latest ChromeDriver version: $LATEST_CHROMEDRIVER_VERSION"
-        wget -N "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
+        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
+        MAJOR_CHROME_VERSION=$(echo $CHROME_VERSION | cut -d. -f1)
+        echo "Chrome version: $CHROME_VERSION"
+        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_CHROME_VERSION)
+        if [ -z "$CHROMEDRIVER_VERSION" ]; then
+          echo "Error: Unable to find ChromeDriver version for Chrome $CHROME_VERSION"
+          exit 1
+        fi
+        wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
         unzip chromedriver_linux64.zip -d /usr/local/bin/
         rm chromedriver_linux64.zip
 
