Update update_token.yml

diff --git a/.github/workflows/update_token.yml b/.github/workflows/update_token.yml
--- a/.github/workflows/update_token.yml
+++ b/.github/workflows/update_token.yml
@@ -33,21 +33,17 @@ jobs:
         run: |
           python scraper.py
 
-      # Check if channels.m3u exists
-      - name: Check if channels.m3u exists
-        run: |
-          ls -l  # Faylları göstərmək üçün ls komutunu istifadə et
-          if [ -f "./channels.m3u" ]; then
-            echo "channels.m3u file found."
-          else
-            echo "channels.m3u file not found!"
-            exit 1
-          fi
-
-      # Upload the artifact (channels.m3u)
-      - name: Upload channels.m3u artifact
-        if: success() && fileExists('channels.m3u')
+      # Check if channels.m3u exists and upload it
+      - name: Upload channels.m3u artifact if exists
+        if: ${{ exists('channels.m3u') }}
         uses: actions/upload-artifact@v4
         with:
           name: channels-m3u
           path: channels.m3u
+
+      # If the file doesn't exist, fail the workflow
+      - name: Fail if channels.m3u not found
+        if: ${{ !exists('channels.m3u') }}
+        run: |
+          echo "channels.m3u file not found!"
+          exit 1
