Update update_token.yml

diff --git a/.github/workflows/update_token.yml b/.github/workflows/update_token.yml
--- a/.github/workflows/update_token.yml
+++ b/.github/workflows/update_token.yml
@@ -19,11 +19,18 @@ jobs:
         python -m pip install --upgrade pip
         pip install selenium
 
+    - name: Install Google Chrome
+      run: sudo apt-get install -y google-chrome-stable
+
     - name: Download ChromeDriver
       run: |
-        sudo apt-get install -y google-chrome-stable
-        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
-        wget -N https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)/chromedriver_linux64.zip
+        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
+        CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
+        if [ -z "$CHROMEDRIVER_VERSION" ]; then
+          echo "Error: Unable to find ChromeDriver version for Chrome $CHROME_VERSION"
+          exit 1
+        fi
+        wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
         unzip chromedriver_linux64.zip -d /usr/local/bin/
 
     - name: Run script
