Update update_token.yml

diff --git a/.github/workflows/update_token.yml b/.github/workflows/update_token.yml
--- a/.github/workflows/update_token.yml
+++ b/.github/workflows/update_token.yml
@@ -27,7 +27,12 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y chromium-browser
         sudo apt-get install -y chromium-chromedriver
-        sudo apt-get install -y libnss3 libgdk-pixbuf2.0-0 libxss1 libgconf-2-4 libatk-bridge2.0-0 libatk1.0-0 libgbm-dev
+        sudo apt-get install -y libnss3 libgdk-pixbuf2.0-0 libxss1 libatk-bridge2.0-0 libatk1.0-0 libgbm-dev
+        sudo apt-get install -y libgconf-2-4 || echo "libgconf-2-4 not found"
+
+    - name: Set Chrome options
+      run: |
+        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
 
     - name: Run token update script
       run: |
